local f = CreateFrame("Frame")
f:RegisterEvent("SHOW_LOOT_TOAST_LEGENDARY_LOOTED")
f:SetScript("OnEvent", function(self)
	PlaySoundFile("Interface\\AddOns\\m4x-Legendary\\legendary.ogg", "Master")
end)